2023-09-03 22:00:18,850 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(524) - Start polling
2023-09-03 22:00:19,875 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1765) - Task exception was never retrieved
future: <Task finished name='Task-30' coro=<update_json() done, defined at /Users/Kafka/PycharmProjects/Jobitt-bot/core/utils/download_data.py:10> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/Users/Kafka/PycharmProjects/Jobitt-bot/core/utils/download_data.py", line 19, in update_json
    with open(filename, 'w') as file:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'sources/main.json'
2023-09-03 22:00:20,388 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1765) - Task exception was never retrieved
future: <Task finished name='Task-32' coro=<check_for_mailing() done, defined at /Users/Kafka/PycharmProjects/Jobitt-bot/core/utils/data_mailing.py:69> exception=UndefinedColumnError('column "block" does not exist')>
Traceback (most recent call last):
  File "/Users/Kafka/PycharmProjects/Jobitt-bot/core/utils/data_mailing.py", line 70, in check_for_mailing
    block = await admins.check_block()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Kafka/PycharmProjects/Jobitt-bot/core/database/db_admins.py", line 88, in check_block
    return await self.connector.fetchval("""
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/asyncpg/pool.py", line 616, in fetchval
    return await con.fetchval(
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/asyncpg/connection.py", line 644, in fetchval
    data = await self._execute(query, args, 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/asyncpg/connection.py", line 1659, in _execute
    result, _ = await self.__execute(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/asyncpg/connection.py", line 1684, in __execute
    return await self._do_execute(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/asyncpg/connection.py", line 1719, in _do_execute
    stmt = await self._get_statement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/asyncpg/connection.py", line 397, in _get_statement
    statement = await self._protocol.prepare(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
asyncpg.exceptions.UndefinedColumnError: column "block" does not exist
2023-09-03 22:00:20,417 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(340) - Run polling for bot @LeonMagnum_bot id=5968452292 - 'Test_my_bot'
2023-09-03 22:00:55,585 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(452) - Received SIGINT signal
2023-09-03 22:00:55,597 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(356) - Polling stopped for bot @LeonMagnum_bot id=5968452292 - 'Test_my_bot'
2023-09-03 22:00:55,598 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(551) - Polling stopped
2023-09-03 22:01:06,491 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(524) - Start polling
2023-09-03 22:01:06,977 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1765) - Task exception was never retrieved
future: <Task finished name='Task-31' coro=<update_json() done, defined at /Users/Kafka/PycharmProjects/Jobitt-bot/core/utils/download_data.py:10> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/Users/Kafka/PycharmProjects/Jobitt-bot/core/utils/download_data.py", line 19, in update_json
    with open(filename, 'w') as file:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'sources/main.json'
2023-09-03 22:01:07,387 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1765) - Task exception was never retrieved
future: <Task finished name='Task-33' coro=<check_for_mailing() done, defined at /Users/Kafka/PycharmProjects/Jobitt-bot/core/utils/data_mailing.py:69> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/Users/Kafka/PycharmProjects/Jobitt-bot/core/utils/data_mailing.py", line 73, in check_for_mailing
    with open('sources/main.json', 'r', encoding='utf-8') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'sources/main.json'
2023-09-03 22:01:07,414 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(340) - Run polling for bot @LeonMagnum_bot id=5968452292 - 'Test_my_bot'
2023-09-03 22:02:42,596 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(452) - Received SIGINT signal
2023-09-03 22:02:42,616 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(356) - Polling stopped for bot @LeonMagnum_bot id=5968452292 - 'Test_my_bot'
2023-09-03 22:02:42,617 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(551) - Polling stopped
2023-09-03 22:02:53,848 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(524) - Start polling
2023-09-03 22:02:54,744 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(340) - Run polling for bot @LeonMagnum_bot id=5968452292 - 'Test_my_bot'
2023-09-03 22:02:55,758 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1765) - Task exception was never retrieved
future: <Task finished name='Task-32' coro=<check_for_mailing() done, defined at /Users/Kafka/PycharmProjects/Jobitt-bot/core/utils/data_mailing.py:69> exception=KeyError('Повний робочий день')>
Traceback (most recent call last):
  File "/Users/Kafka/PycharmProjects/Jobitt-bot/core/utils/data_mailing.py", line 130, in check_for_mailing
    if user['job_type'] != is_type[row['work_type']]:
                           ~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'Повний робочий день'
2023-09-03 22:04:06,683 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(452) - Received SIGINT signal
2023-09-03 22:04:06,690 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(356) - Polling stopped for bot @LeonMagnum_bot id=5968452292 - 'Test_my_bot'
2023-09-03 22:04:06,690 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(551) - Polling stopped
2023-09-03 22:04:22,495 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(524) - Start polling
2023-09-03 22:04:23,355 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(340) - Run polling for bot @LeonMagnum_bot id=5968452292 - 'Test_my_bot'
2023-09-03 22:04:29,110 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1765) - Task exception was never retrieved
future: <Task finished name='Task-33' coro=<check_for_mailing() done, defined at /Users/Kafka/PycharmProjects/Jobitt-bot/core/utils/data_mailing.py:69> exception=KeyError('Повний робочий день')>
Traceback (most recent call last):
  File "/Users/Kafka/PycharmProjects/Jobitt-bot/core/utils/data_mailing.py", line 130, in check_for_mailing
    if user['job_type'] != is_type[row['work_type']].lower:
                           ~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'Повний робочий день'
2023-09-03 22:05:15,543 - [INFO] - aiogram.event - (dispatcher.py).feed_update(171) - Update id=497636430 is handled. Duration 377 ms by bot id=5968452292
2023-09-03 22:05:16,952 - [INFO] - aiogram.event - (dispatcher.py).feed_update(171) - Update id=497636431 is handled. Duration 269 ms by bot id=5968452292
2023-09-03 22:05:19,227 - [INFO] - aiogram.event - (dispatcher.py).feed_update(171) - Update id=497636432 is handled. Duration 438 ms by bot id=5968452292
2023-09-03 22:05:21,644 - [INFO] - aiogram.event - (dispatcher.py).feed_update(171) - Update id=497636433 is handled. Duration 631 ms by bot id=5968452292
2023-09-03 22:05:54,865 - [INFO] - aiogram.event - (dispatcher.py).feed_update(171) - Update id=497636434 is not handled. Duration 55 ms by bot id=5968452292
2023-09-03 22:05:54,868 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(314) - Cause exception while process update id=497636434 by bot id=5968452292
IndeterminateDatatypeError: cannot determine type of empty array
HINT:  Explicitly cast to the desired type, for example ARRAY[]::integer[].
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/Kafka/PycharmProjects/Jobitt-bot/core/handlers/admins/technologies.py", line 53, in settings
    await admins.remove_all_technologies()
  File "/Users/Kafka/PycharmProjects/Jobitt-bot/core/database/db_admins.py", line 76, in remove_all_technologies
    await self.connector.execute("""
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/asyncpg/pool.py", line 567, in execute
    return await con.execute(query, *args, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/asyncpg/connection.py", line 317, in execute
    return await self._protocol.query(query, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 338, in query
asyncpg.exceptions.IndeterminateDatatypeError: cannot determine type of empty array
HINT:  Explicitly cast to the desired type, for example ARRAY[]::integer[].
2023-09-03 22:06:14,556 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(452) - Received SIGINT signal
2023-09-03 22:06:14,573 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(356) - Polling stopped for bot @LeonMagnum_bot id=5968452292 - 'Test_my_bot'
2023-09-03 22:06:14,575 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(551) - Polling stopped
2023-09-03 22:06:26,460 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(524) - Start polling
2023-09-03 22:06:27,427 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(340) - Run polling for bot @LeonMagnum_bot id=5968452292 - 'Test_my_bot'
2023-09-03 22:06:31,429 - [INFO] - aiogram.event - (dispatcher.py).feed_update(171) - Update id=497636435 is not handled. Duration 93 ms by bot id=5968452292
2023-09-03 22:06:31,431 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(314) - Cause exception while process update id=497636435 by bot id=5968452292
PostgresSyntaxError: syntax error at or near "["
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/Kafka/PycharmProjects/Jobitt-bot/core/handlers/admins/technologies.py", line 53, in settings
    await admins.remove_all_technologies()
  File "/Users/Kafka/PycharmProjects/Jobitt-bot/core/database/db_admins.py", line 76, in remove_all_technologies
    await self.connector.execute("""
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/asyncpg/pool.py", line 567, in execute
    return await con.execute(query, *args, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/asyncpg/connection.py", line 317, in execute
    return await self._protocol.query(query, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 338, in query
asyncpg.exceptions.PostgresSyntaxError: syntax error at or near "["
2023-09-03 22:07:16,150 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(452) - Received SIGINT signal
2023-09-03 22:07:16,164 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(356) - Polling stopped for bot @LeonMagnum_bot id=5968452292 - 'Test_my_bot'
2023-09-03 22:07:16,166 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(551) - Polling stopped
2023-09-03 22:07:31,158 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(524) - Start polling
2023-09-03 22:07:31,995 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(340) - Run polling for bot @LeonMagnum_bot id=5968452292 - 'Test_my_bot'
2023-09-03 22:07:34,368 - [INFO] - aiogram.event - (dispatcher.py).feed_update(171) - Update id=497636436 is handled. Duration 334 ms by bot id=5968452292
2023-09-03 22:07:49,081 - [INFO] - aiogram.event - (dispatcher.py).feed_update(171) - Update id=497636437 is handled. Duration 1067 ms by bot id=5968452292
2023-09-03 22:07:51,318 - [INFO] - aiogram.event - (dispatcher.py).feed_update(171) - Update id=497636438 is handled. Duration 555 ms by bot id=5968452292
2023-09-03 22:07:53,328 - [INFO] - aiogram.event - (dispatcher.py).feed_update(171) - Update id=497636439 is handled. Duration 556 ms by bot id=5968452292
2023-09-03 22:08:05,947 - [INFO] - aiogram.event - (dispatcher.py).feed_update(171) - Update id=497636440 is handled. Duration 379 ms by bot id=5968452292
2023-09-03 22:08:08,102 - [INFO] - aiogram.event - (dispatcher.py).feed_update(171) - Update id=497636441 is handled. Duration 380 ms by bot id=5968452292
